### ISSUE TITLE
failed to get status from unifi: very host,port,user name, and password are correct error code

### ISSUE THREAD

**Issue by ray10diaz** [derek-miller/homebridge-unifi-smartpower#11]
**Describe Your Problem:**

I get the following issue: "[12/12/2022, 12:38:34 AM] [UniFi SmartPower] Failed to get status from UniFi; verify host, port, username, and password are correct"
**Logs:**

```
[12/12/2022, 12:38:34 AM] [UniFi SmartPower] Failed to get status from UniFi; verify host, port, username, and password are correct
```

**Plugin Config:**  x= redacted info

```json
{
    "bridge": {
        "name": "Homebridge ",
        "username": xxxxxxx",
        "port": 51773,
        "pin": xxxxxxx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-blue",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "10.xx.xx.1",
                    "password": "xxxx",
                    "username": "xxxx"
                }
            ],
            "platform": "UniFi Protect",
            "_bridge": {
                "username": "xxxx",
                "port": 46726
            }
        },
        {
            "name": "UniFi SmartPower",
            "host": "10.xx.xx.1",
            "port": 443,
            "username": "hxxxxxSP",
            "password": "xxxxxx",
            "refreshDevicesPollInterval": 600,
            "outletStatusCacheTtl": 15,
            "outletStatusPollInterval": 15,
            "platform": "UniFiSmartPower"
        }
```

**Screenshots:**

**Environment:**

- **Plugin Version**: 0.4.1
- **Homebridge Version**: [v1.6.0]
- **Node.js Version**: [v18.12.1]
- **NPM Version**: 8.19.2
- **Operating System**: <Ubuntu server 22.04>

**Comment by derek-miller** [comment]
Is your user assigned to a role with "Full Management" privileges to the Network application?
<img width="1957" alt="image" src="https://user-images.githubusercontent.com/1340081/207371280-b95a907e-5aec-427a-bd67-a871898e7646.png">

**Comment by derek-miller** [comment]
Please update to v0.4.2. I added some additional context to the log message that may help narrow down your issue. Also, what are you using as your UniFi console (e.g. UDM, UDM-Pro, UDM-SE, Cloud Key, Cloud Key Gen 2, etc)?

**Comment by ray10diaz** [comment]
Hi, sorry I didn't get a notification for your first reply. My apologies. I upgraded just now. I'm running my unifi OS on a UDM:SE. Do you know how to get the logs? Could the issue be I'm on early access firmware for my unifi OS?

**Comment by ray10diaz** [comment]
Okay never mind. I see error code 403. See image ![image](https://user-images.githubusercontent.com/13565038/208228858-0e509b84-cde7-4358-8c44-db4673c78eca.png)

**Comment by derek-miller** [comment]
I double checked and a 403 could mean your username/password is incorrect (usually this a 401, but the API does not treat it this way), or the user does not have privileges to access the network application API.

**Comment by ray10diaz** [comment]
I changed the password and still get the same issue. Just copy and paste it when I change it. I run unifi protect on my home bridge as well with the same info and controller ip.

**Comment by derek-miller** [comment]
What are the permissions set to for the user you are using?

**Comment by ray10diaz** [comment]
I figured it out. One of my projects was to put homebridge in docker and I did. It worked when I put it on rocker. Probably there was inference with my AdGuard home. Idk what the issue could be. I figured it out at last. Thank you for your help. I really appreciate it and happy holidays

**Comment by derek-miller** [comment]
No worries. Glad you got it working!
