### ISSUE TITLE
Outlet Names

### ISSUE THREAD

**Issue by RetroTuners** [derek-miller/homebridge-unifi-smartpower#13]
I noticed that each outlet is just named
Outlet 1 
Outlet 2 
Outlet 3 
Outlet 4
Outlet 5
Outlet 6 
USB

Can we have an options to change the names

X-Mas Tree
TV
Charger for MacBook
Etc Etc Etc

**Comment by derek-miller** [comment]
The plugin uses the names set in the UniFi console, however HomeKit has a bug that does not use them correctly on import. You can verify this by clicking the "X" next to the accessory name in HomeKit and the placeholder text in the input will be the name of the outlet in the UniFi console during import. HomeKit does not allow changing names of accessories by bridges after initial import.

https://user-images.githubusercontent.com/1340081/207437839-f08d6ef9-b7d6-453a-978c-142192b10944.mp4
