### ISSUE TITLE
Port Number

### ISSUE THREAD

**Issue by montee22** [derek-miller/homebridge-unifi-smartpower#26]
Hello,
Thanks for the plugin. I have one quick question. Which port should I forward in UniFi SmartPower Plugin? Do I also need to forward port in UDMPRO port forward settings? If yes, then should I use Dest/IP of the smartpower or the my Unifi smartpower IP? Or do I need to change any other settings? 
Please advice
Thanks

**Comment by derek-miller** [comment]
You use the port for your controller.
