### ISSUE TITLE
Expose wattage usage so that Eve and other 3rd party apps can view.

### ISSUE THREAD

**Issue by dsully** [derek-miller/homebridge-unifi-smartpower#34]
**Is your feature request related to a problem? Please describe:**

It would be nice if you could expose the wattage output of each Outlet / Port, and using 

https://github.com/simont77/fakegato-history

to let Eve and other 3rd party apps access the persisted data to graph over time.

**Comment by derek-miller** [comment]
I don’t use eve so not sure when I will get to this. If you want to give it a shot I would accept a pull request.
