### ISSUE TITLE
Post UDM/NVR Upgrade, Cannot Log Into Console 

### ISSUE THREAD

**Issue by T3LC0** [derek-miller/homebridge-unifi-smartpower#36]
**Describe Your Problem:** 
After Update to OS Console (Running the 3.x) series. The plugin is no longer able to login to the console and control any switches/plugs.  This has worked great for months but no longer. No user account changes were made on the UDM.  

**Logs:**
[10/24/2023, 11:12:34 AM] [UniFi SmartPower] Failed to get sites from UniFi; verify host, port, username, and password are correct:  AxiosError: Request failed with status code 401
    at settle (/var/lib/homebridge/node_modules/homebridge-unifi-smartpower/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-unifi-smartpower/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Plugin Config:**

{
            "name": "UniFi SmartPower",
            "host": "192.168.X.X",
            "port": 443,
            "username": "<Redacted>",
            "password": "<Redacted>",
            "controlSwitch": {
                "create": true,
                "name": "UniFi Control Enabled",
                "timeout": 60,
                "guardOutlets": false,
                "guardSwitchPorts": true
            },
            "includeInactivePorts": false,
            "refreshDevicesPollInterval": 600,
            "outletStatusCacheTtl": 15,
            "outletStatusPollInterval": 15,
            "logApiResponses": true,
            "platform": "UniFiSmartPower"
        },

**Environment:**

- **Plugin Version:** homebridge-unifi-smartpower v2.1.0
- **Homebridge Version:** v1.6.1
- **Node.js Version:** v18.18.2
- **NPM Version:** 9.8.1
- **Operating System:** Ubuntu 22.04.3 LTS - LXC Container running on Proxmox 7.4.17
- ** UDM Version:** Network 8.0.2, UniFi OS 3.2.5

**Comment by derek-miller** [comment]
Network version 8.0.2 is an EA version and I do not want to support unreleased versions as they are a pretty fast moving target with frequent issues. When it lands GA I will update the plugin.

**Comment by T3LC0** [comment]
Are you interested in at least seeing some debug logging to prep for the transition. Looks like the API changed and I can at least get you a sneak preview of it with some debug logging.

**Comment by derek-miller** [comment]
Yeah, any info would be appreciated. I have been bit in the past by running EA versions and I now wait for the GA releases and don't have a spare controller to test with.

**Comment by rennsport** [comment]
Hey @derek-miller, as a follow up to this issue, Network Application version 8.x was released to the public 5 days ago https://community.ui.com/releases/UniFi-Network-Application-8-0-7/7818b9df-4845-4c82-ba3c-1218e61010d4

Not expecting such a short turnaround at all, but just wanted to bring it to your attention in case you hadn't seen yet.

**Comment by derek-miller** [comment]
I published v2.1.1 which will fix this issue.
