### ISSUE TITLE
Support for RPS

### ISSUE THREAD

**Issue by mpreissner** [derek-miller/homebridge-unifi-smartpower#42]
Would love to see support for the USP-RPS so we could disable/enable the DC power ports for supported gear.  This would allow us to actually power cycle devices that are connected to the RPS by creating automations that first disable the RPS port for the connected device, and then bounce the PDU AC Outlet for that device.  Without this, bouncing the AC Outlet on the PDU doesn't do anything as the device would failover to DC power via the RPS.

**Comment by derek-miller** [comment]
Should be easy to do. I actually have an RPS to test with too. I will look into it soon.

**Comment by derek-miller** [comment]
This is added in v2.2.0
